----    01 Test 1
----    Input
----    Expected output
----    String
----    6 gnirts
----    02 Test 2
----    Input
----    Expected output
----    variable
----    8 elbairav
----    03 Test 3
----    Input
----    Expected output
----    pointer
----    7 retniop
----    04 Test 4
----    Input
----    Expected output
----    Function
----    8 noitcnuf

--create table reverse_and_counter(
--str_ varchar(255)
--);
--insert into reverse_and_counter values ('String'), ('variable'), ('pointer'), ('Function'), (''), ('two words')

--select str_, CONCAT(len(str_), ' ', REVERSE(str_)) sol from reverse_and_counter